[features]
seeds = false
[programs.localnet]
escrowdemo = "HadGeJ6KCGiyzVTe13n5TY1rCSEyd9Akgx7cYBvYx5Dt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/antoineherzog/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
